version: "3.8"
services:

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
#      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
#      - MONGO_INITDB_ROOT_PASSWORD=podiyumm
      - MONGO_INITDB_DATABASE=podiyumm
#    volumes:
#      - ${PWD}/mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped