quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017/podiyumm?socketTimeoutMS=1000&connectTimeoutMS=1000&serverSelectionTimeoutMS=1000
    write-concern:
      journal: false
    database: podiyumm
  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.xml

"%dev":
  http:
    cors:
      ~: true
      origins: http://localhost:3000
      methods: GET,PUT,POST
      headers: X-Custom
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true

"%prod":

  quarkus:
    vault:
      url: http://vault:8200
      credentials-provider:
        podiyumm:
          database-credentials-role: podiyumm-song
