name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      # share artifact across jobs
      - name: 'Tar files'
        run: tar -cvf quarkus-app.tar build/lib build/*-runner.jar
      - uses: actions/upload-artifact@v2
        with:
          name: quarkus-app
          path: quarkus-app.tar

  docker:
    name: docker
    runs-on: ubuntu-latest
    needs: build
#    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      # share artifact across jobs
      - uses: actions/download-artifact@v2
        with:
          name: quarkus-app
      - name: 'Untar files'
        run: tar -xvf quarkus-app.tar
      - uses: madhead/read-java-properties@latest
        id: props
        with:
          file: gradle.properties
          all: true
      # build + push docker img
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (jvm)
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./src/main/docker/Dockerfile.jvm
          push: true
          tags: podiyumm/podiyumm-song:${{ steps.props.outputs.version }}
